version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://db:5432/kanban-todo
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=kanban-todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: