services:
  - type: web
    name: quarkus-kanban-todo
    runtime: docker
    buildCommand: |
      ./mvnw package -DskipTests
      docker build -t quarkus-todo .
    startCommand: java $JAVA_OPTS -jar target/quarkus-app/quarkus-run.jar
    envVars:
      - key: PORT
        value: 8080
      - key: POSTGRES_URL
        fromDatabase:
          name: kanban-todo
          property: connectionString
      - key: POSTGRES_USER
        fromDatabase:
          name: kanban-todo
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: kanban-todo
          property: password

databases:
  - name: kanban-todo
    databaseName: todo
    plan: free
