services:
  - type: web
    name: quarkus-todo
    env: docker
    buildCommand: ./mvnw package -Dmaven.test.skip=true
    startCommand: java $JAVA_OPTS -jar target/quarkus-app/quarkus-run.jar
    envVars:
      - key: PORT
        value: 8080
      - key: POSTGRES_URL
        fromDatabase:
          name: todo-db
          property: connectionString
      - key: POSTGRES_USER
        fromDatabase:
          name: todo-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: todo-db
          property: password

databases:
  - name: todo-db
    databaseName: todo
    plan: free
